[workspace]
members = [
	"contract-address",
	"fixed-hash",
	"keccak-hash",
	"kvdb",
	"kvdb-memorydb",
	"kvdb-rocksdb",
	"kvdb-shared-tests",
	"kvdb-web",
	"parity-bytes",
	"parity-crypto",
	"parity-path",
	"plain_hasher",
	"rlp",
	"rlp-derive",
	"runtime",
	"transaction-pool",
	"trace-time",
	"triehash",
	"uint",
	"parity-util-mem",
	"primitive-types",
	"ethereum-types",
	"ethbloom",
	"parity-util-mem/derive"
]

[patch.crates-io]
librocksdb-sys = { git = "https://github.com/aleksuss/rust-rocksdb", branch = "fix_win_build" }
